### ISSUE TITLE
Issue with Demo JPA

### ISSUE THREAD

**Issue by jvargh** [dlbunker/ps-spring-boot-resources#1]
Any thoughts around this? Fails in module 'Configuring Data Source' as part of the last step, completing the app

2016-04-08 10:41:59.886 ERROR 13028 --- [nio-8080-exec-3] o.h.engine.jdbc.spi.SqlExceptionHelper   : Column "LONGITUDE" not found; SQL statement:
insert into shipwreck (id, condition, depth, description, latitude, longitude, name, year_discovered) values (null, ?, ?, ?, ?, ?, ?, ?) [42122-191]

**Comment by dlbunker** [comment]
What does your shipwreck table definition look like?  You can use the H2 console to look at that.  By the error I'm guessing that the longitude column is missing so we'd need to figure out if a flyway migration didn't run.  You can also check the schema_migration table data to see what migrations have run and what migration version the database is at.
