### ISSUE TITLE
'could not prepare statement' Error

### ISSUE THREAD

**Issue by jvargh** [dlbunker/ps-spring-boot-resources#2]
After autowiring ShipwreckRepository in controller and invoking any of the CRUD methods, it results in below  error. This is after following all steps to configure and access a data store. Any thoughts would be appreciated

Mon Jun 06 23:50:57 EDT 2016
There was an unexpected error (type=Internal Server Error, status=500).
could not prepare statement; SQL [select shipwreck0_.id as id1_0_0_, shipwreck0_.condition as conditio2_0_0_, shipwreck0_.depth as depth3_0_0_, shipwreck0_.description as descript4_0_0_, shipwreck0_.latitude as latitude5_0_0_, shipwreck0_.longitude as longitud6_0_0_, shipwreck0_.name as name7_0_0_, shipwreck0_.year_discovered as year_dis8_0_0_ from shipwreck shipwreck0_ where shipwreck0_.id=?]; nested exception is org.hibernate.exception.SQLGrammarException: **could not prepare statement**

**Comment by lastmaj** [comment]
I have bumped into the same error and have been looking for an answer online but could not find
Please share a solution if any.

**Comment by sanishmr** [comment]
Hello,
any luck on this ? not sure how column name YEARDISCOVERED getting changed to YEAR_DISCOVERED.

> ERROR 5532 --- [nio-8080-exec-7] o.h.engine.jdbc.spi.SqlExceptionHelper   : Column "SHIPWRECK0_.YEAR_DISCOVERED" not found; SQL statement:
select shipwreck0_.id as id1_0_, shipwreck0_.condition as conditio2_0_, shipwreck0_.depth as depth3_0_, shipwreck0_.description as descript4_0_, shipwreck0_.latitude as latitude5_0_, shipwreck0_.longitude as longitud6_0_, shipwreck0_.name as name7_0_, shipwreck0_.year_discovered as year_dis8_0_ from shipwreck shipwreck0_ [42122-197]

>  ERROR 5532 --- [nio-8080-exec-7] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.dao.InvalidDataAccessResourceUsageException: could not prepare statement; SQL [select shipwreck0_.id as id1_0_, shipwreck0_.condition as conditio2_0_, shipwreck0_.depth as depth3_0_, shipwreck0_.description as descript4_0_, shipwreck0_.latitude as latitude5_0_, shipwreck0_.longitude as longitud6_0_, shipwreck0_.name as name7_0_, shipwreck0_.year_discovered as year_dis8_0_ from shipwreck shipwreck0_]; nested exception is org.hibernate.exception.SQLGrammarException: could not prepare statement] with root cause

> org.h2.jdbc.JdbcSQLException:  Column "SHIPWRECK0_.YEAR_DISCOVERED" not found; SQL statement:
select shipwreck0_.id as id1_0_, shipwreck0_.condition as conditio2_0_, shipwreck0_.depth as depth3_0_, shipwreck0_.description as descript4_0_, shipwreck0_.latitude as latitude5_0_, shipwreck0_.longitude as longitud6_0_, shipwreck0_.name as name7_0_, shipwreck0_.year_discovered as year_dis8_0_ from shipwreck shipwreck0_ [42122-197]

Thanks
Sanish

**Comment by Gabriel008** [comment]
Me a pasado lo mismo alguna solución que conozcan?
